require("dotenv").config();
const { generateProof, verifyProof } = require("../services/zkpService");

// Service test for ZKP backend, generated by ChatGPT o3-mini model
async function runCycle() {
  try {
    // Define public input and private indices for generating a proof.
    const level = [1, 2, 3, 4];          // Example public input array.
    const user_indices = [0, 1, 2];        // Example private indices.

    console.log("Requesting proof generation...");
    // Generate the proof from the ZKP backend.
    const proofResponse = await generateProof(level, user_indices);
    console.log("Proof generation response:", proofResponse);

    // The response from generateProof is expected to have:
    //   { proof: String, verifying_key: String }
    // Destructure using the same key name as returned.
    const { proof, verifying_key } = proofResponse;

    console.log("Now verifying the generated proof...");
    // Use the same public input and the returned proof and verifying key to verify the proof.
    const verifyResponse = await verifyProof(level, proof, verifying_key);
    console.log("Proof verification response:", verifyResponse);

    if (verifyResponse.proof_status) {
      console.log("Proof verified successfully!");
    } else {
      console.log("Proof verification failed.");
    }
  } catch (error) {
    console.error("Error during proof cycle:", error.message);
  }
}

runCycle();
